tags:
  - name: auth
    description: user authentication
  - name: interest
    description: user interests
  - name: user
    description: user info
  - name: post
    description: user post

paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: User Signup
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/createUser"
          required: true
      responses:
        201:
          description: "successfully creates user"
        400:
          description: "Bad Request"
        500:
          description: "Internal Server Error"

  /auth/login:
    post:
      tags:
        - auth
      summary: User Login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/loginUser"
          required: true
      responses:
        200:
          description: "returns authentication token"
        400:
          description: "Bad Request"
        404:
          description: "User not found"
        409:
          description: "Incorrect user inputs"
        500:
          description: "Internal Server Error"

  /interest/interests:
    get:
      tags:
        - interest
      summary: Fetches all Interests
      produces:
        - application/json
      responses:
        200:
          description: "A list of all interests"
        500:
          description: "Internal Server Error"

/user/user-details:
  get:
    tags:
      - user
    summary: User Details
    description: All associated user details for the profile
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
    responses:
      200:
        description: "Show user profile data"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

/post/create-post:
  post:
    tags:
      - post
    summary: Create Post
    description: User creates a post
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
      - name: body
        in: body
        schema:
          $ref: "#/definitions/createPost"
        required: true
    responses:
      201:
        description: "Successfully creates a post"
      400:
        description: "Bad request"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

/post/other-posts:
  get:
    tags:
      - post
    summary: Other Users Posts
    description: Get all posts from other users
    consumes:
      - application/json
    produces:
      - application/json
    parameters:
      - name: Authorization
        in: header
        description: Authorization token
        required: true
        type: string
    responses:
      200:
        description: "Show user profile data"
      401:
        description: "User authentication fails"
      500:
        description: "Internal Server Error"

# --------------------------definitions--------------------------
definitions:
  createUser:
    type: object
    required:
      - firstName
      - lastName
      - email
      - interestId
      - password
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password
      interestId:
        type: integer

  loginUser:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password

  createPost:
    type: object
    required:
      - title
      - content
    properties:
      title:
        type: string
      content:
        type: string
